apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app1_access_role
  namespace: app1-namespace
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

