apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      initContainers:
        - name: init-cont-app1
          image: dockerbymariam/app1_nginx:latest
          command:
            - sh
            - -c
            - |
              if [ ! -f /mnt/html/index.html ]; then
                echo "Copying index.html to PV"
                cp /usr/share/nginx/html/index.html /mnt/html/index.html
              else
                echo "index.html already exists, skipping"
              fi
          volumeMounts:
            - name: app1-pv
              mountPath: /mnt/html
      containers:
      - name: app1-container
        image: dockerbymariam/app1_nginx:latest
        volumeMounts:
          - name: app1-pv
            mountPath: /usr/share/nginx/html/
        ports:
        - containerPort: 80
      volumes:
      - name: app1-pv
        persistentVolumeClaim:
          claimName: app1-pvc


