apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: app1-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-nginx
  template:
    metadata:
      labels:
        app: app1-nginx
    spec:
      containers:
      - name: app1-container
        image: dockerbymariam/app1_nginx:latest
        volumeMounts:
          - name: app1-pv
            mountPath: /usr/share/nginx/html/
        ports:
        - containerPort: 80
      volumes:
      - name: app1-pv
        persistentVolumeClaim:
          claimName: app1-pvc


