apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1_access_roleBinding
  namespace: app1-namespace
subjects:
- kind: User
  name: nginx_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app1_access_role
  apiGroup: rbac.authorization.k8s.io

