apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app2_access_roleBinding
  namespace: app2-namespace
subjects:
- kind: User
  name: nginx_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: app2_access_role
  apiGroup: rbac.authorization.k8s.io


