apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: app2-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2-nginx
  template:
    metadata:
      labels:
        app: app2-nginx
    spec:
      containers:
      - name: app2-container
        image: dockerbymariam/app2_nginx:latest
        ports:
        - containerPort: 80


