apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app2_access_role
  namespace: app2-namespace
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

